config/routes.rb
Rails.application.routes.draw do
  # resources :categories
  get 'home/index' 
  # resources :home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  
  resources :categories do
    resources :expenses
  end
  root "home#index"
end

app/views/shared/_grid-20.html.erb
<div class='grid-20'>
  <div class="">
    <div class="profile-name">
      <% if user_signed_in? %>
        <% if current_user.avatar.present? %>
          <%= image_tag(current_user.avatar.url, class: "avatar") %>
        <% else %>
          <%= image_tag("profile.png", class: "avatar") %>
        <% end %>
      <% end %>
      <p class="username small-fade"><%= current_user.name %></p>
    </div>
    
    <div class="quick-stats">
      <% if @categories.empty?%>
      <p class='no-categories'>You have no categories yet</p>
      <% else %>
        <p class="fade-text">You have <%= @categories.length %> <%= 'category'.pluralize(@categories.length) %></p>
        <p class="fade-text">Total categories budget <%= number_to_currency(@total_sum_categories.sum(:limit)) %></p>
      <% end %>
    </div>
  </div>
  <div>
    <div>
      <div class="mini-add-option">
        <p class='latest-categories-ribbon'>Latest Categories</p>
        <p ><%= link_to "+", new_category_path,  class: "plus-category"%></p>
      </div>
      <div>
      </div>
      <div class="latest-categories">
        <% @latest.each do |category| %>
          <div class="type-and-number">
            <div class="name-and-amt-spent">
              <%= link_to category.name, category_expenses_path(category_id: category.id), class: 'category_name' %>
              <p class="small-fade spent"> <%= number_to_currency(category.expenses.sum(:amount)) %> spent</p>
            </div>
              <% if category.expenses.length == 0%>
                <p class="small-fade spent items">No expense</p>
                <% else%> 
                <p class="small-fade spent items"><%= category.expenses.length %> <%= 'Item'.pluralize(category.expenses.count) %></p>
              <%end%>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<header class='desktop-header'>
  <nav class="nav">
    <%= link_to categories_path, class: 'back-sign'  do%>
      <%= image_tag 'logo.png', class: 'nav-main'%>
    <% end %>
    <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "submit-button" %>
  </nav>
</header>

<header class='mobile-header'>
  <nav class="mobile-nav">
    <%= link_to categories_path, class: 'back-sign'  do%>
      <%= image_tag 'logo.png', class: 'everest-logo nav-main' %>
    <% end %>
    <ul class='mobile-ul'>
      <li><%= button_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-sign-out" %></li>
      <div class="profile-name-mobile"> 
        <% if user_signed_in? %>
          <% if current_user.avatar.present? %>
            <%= image_tag(current_user.avatar.url, class: "avatar") %>
          <% else %>
            <%= image_tag("profile.png", class: "avatar") %>
          <% end %>
        <% end %>
        <li class="username small-fade"><%= current_user.name %></li>
      </div>
    </ul>
  </nav>
</header>