config/routes.rb
Rails.application.routes.draw do
  # resources :categories
  get 'home/index' 
  # resources :home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  
  resources :categories do
    resources :expenses
  end
  root "home#index"
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :expenses

  validates :name, presence: true, length: { maximum: 50 }
  validates :limit, numericality: { less_than: 1_000_000 }
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[edit update destroy]
  before_action :set_stat_div, only: %i[index new edit update create]

  # GET /categories or /categories.json
  def index; end

  # GET /categories/1 or /categories/1.json
  def show; end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories or /categories.json
  def create
    @category = current_user.categories.new(category_params)

    if @category.name.blank? || @category.limit.blank?
      redirect_to new_category_path(author_id: current_user.id)
      flash[:notice] = 'Name and limit are required'
    elsif @category.limit > 1_000_000
      redirect_to new_category_path(author_id: current_user.id)
      flash[:notice] = 'Limit cannot exceed $1,000,000'
    elsif @category.save
      redirect_to categories_path
      flash[:notice] = 'Successfully created a category 🎉!'
    else
      render :new
    end
  end

  def set_stat_div
    @categories = current_user.categories.includes(:expenses).order(created_at: :desc)
    @latest = current_user.categories.includes(:expenses).order(created_at: :desc).limit(3)
    @total_sum_categories = current_user.categories
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    @category = Category.find(params[:id])
    @categories = Category.all

    if @category.expenses.sum(:amount) > params[:category][:limit].to_i
      flash[:notice] =
        'Your limit must be that same or equal to existing expenses for this category. Please increase limit.'
      redirect_to edit_category_path(@category)
    elsif @category.update(category_params)
      redirect_to categories_path
      flash[:notice] = 'Update successful 😊!'
    else
      render :edit
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
    flash[:notice] = 'Category deleted 👋'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :limit)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def generate_color(category_name)
    @color_cache ||= {}
    @color_cache[category_name] ||= generate_random_color
  end

  private

  def generate_random_color
    pastel_colors = ['#ffb6c1', '#b0e0e6', '#98fb98', '#e6e6fa']
    unused_colors = pastel_colors - @color_cache.values
    if unused_colors.empty?
      @color_cache.clear
      unused_colors = pastel_colors
    end
    color = unused_colors.sample
    @color_cache.invert[color] = color
  end
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>"  class='category-details'>
  <div class='category-name-date' >
    <p class="generate-category-avatar align-avatar" style="background-color: <%= generate_color(category.name) %>"><%= category.name[0].upcase %></p>
    <div class='category-date'>
      <%= link_to category.name, category_expenses_path(category_id: category.id), class: 'category_name cat-name-link' %>
      <p class='small-fade created'>Created <%= category.created_at.strftime('%B %e, %Y') %></p>
    </div>
  </div>
  <div class='limit-balance'>
    <div>
      <p class="small-fade category-limit">
        Limit: <%= number_to_currency(category.limit)%>
      </p>
      <% total_amount = category.expenses.sum(:amount) %>
      <p class="small-fade bal">
        <% if category.limit.present? %>
          Bal: <%= number_to_currency(category.limit - total_amount) %>
        <% else %>
          Bal: N/A
        <% end %>
      </p>
    </div>
  </div>
</div>

app/views/categories/_form.html.erb
<div class="">
  <%= form_with(model: category) do |form| %>
    <div>
      <%= form.text_field :name, class: "form-input", placeholder: 'Name'%>
    </div>

    <div>
      <%= form.number_field :limit, class: "form-input", placeholder: 'Limit' %>
    </div>

    <div class="submission-btn-div">
      <%= form.submit class: "submit-button" %>
      <%= link_to "Go Back", request.referrer || root_path, class: "submit-button"  %>
    </div>
  <% end %>
</div>
 

app/views/categories/edit.html.erb
<div class='category-index'>
  <div class='category-card'>
    <div class='grid-80'>
      <div class="inner-layer">
        <%= render partial: 'shared/nav' %>
        <div class="form-div">
          <%= flash[:notice] %>
          <h3 class="form-ribbon">Editing <%= @category.name %>  </h3>
          <%= render "form", category: @category %>
        </div>
      </div>
    </div>
    <%= render partial: 'shared/grid-20' %>
  </div>
</div>

app/views/categories/index.html.erb
<div class='category-index'>
  <div class='category-card'>
    <div class='grid-80'>
      <div class="inner-layer">
        <%= render partial: 'shared/nav' %> 
          <div class="add-category-div">
            <p class='notice' style="color: green"><%= notice %></p>
            <div class='plus-to-add-category-div'>
              <p class="plus-and-text"><%= link_to "+", new_category_path, class: 'add-category-btn'%>Add New Category</p>
            </div>
            <div class='date-today-div'>
              <p class="date-today">Today <%= Time.now.strftime("%a, %d %B %Y") %></p>
            </div>
          </div>
          <div id="categories" class="allCategories">
            <% if @categories.empty?%>
              <p class='no-categories'>You have no categories yet</p>
            <% else %>
              <% @categories.each do |category| %>
                <div class='eachCategory'>
                  <div>
                    <%= render category %>
                  </div>
                  <div class='delete-edit'>
                    <%= link_to edit_category_path(id: category.id) do %>
                      <%= image_tag 'editing.png', class: 'edit-pen' %>
                    <% end %>
                    <p class="fade-text"> <%= button_to 'X', category_path(category), method: :delete, class: 'category_delete_botton' %> </p>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
          <br>
      </div>
    </div>
    <%= render partial: 'shared/grid-20' %>
  </div>
</div>

app/views/categories/new.html.erb
<div class='category-index'>
  <div class='category-card'>
    <div class='grid-80'>
      <div class="inner-layer">
        <%= render partial: 'shared/nav' %>
        <div class="form-div">
          <h3 class="form-ribbon">Add a new category</h3>
          <%= render "form", category: @category %>
        </div>
      </div>
    </div>
    <%= render partial: 'shared/grid-20' %>
  </div>
</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @category %>

<div>
  <%= link_to "Edit this category", edit_category_path(@category) %> |
  <%= link_to "Back to categories", categories_path %>

  <%= button_to "Destroy this category", @category, method: :delete %>
</div>