config/routes.rb
Rails.application.routes.draw do
  # resources :categories
  get 'home/index' 
  # resources :home
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users
  
  resources :categories do
    resources :expenses
  end
  root "home#index"
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  # before_action :set_expense, only: %i[ show edit update destroy ]
  before_action :set_category, only: %i[index new create]
  before_action :set_stat_div, only: %i[index new edit update create]

  # GET /expenses or /expenses.json
  def index
    @category_expenses = Expense.where(category_id: params[:category_id])
    @expenses = @category.expenses.includes(:user).order(created_at: :desc)
    @total_amount = @expenses.sum(:amount)
    @category = Category.find(params[:category_id])
  end

  # GET /expenses/1 or /expenses/1.json
  def show
    @category = Category.find(params[:category_id])
    @expense = @category.expenses.find(params[:id])
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
    @category_expenses = @category.expenses.to_a
    @total_amount = @category_expenses.sum(&:amount)
  end

  # GET /expenses/1/edit
  def edit
    @category = Category.find(params[:category_id])
    @expense = Expense.find(params[:id])
  end

  def set_stat_div
    @categories = current_user.categories.includes(:expenses).order(created_at: :desc)
    @latest = current_user.categories.includes(:expenses).order(created_at: :desc).limit(3)
    @total_sum_categories = current_user.categories
  end

  # POST /expenses or /expenses.json

  def create
    @expense = @category.expenses.build(expense_params)

    if @expense.amount.present? && BigDecimal(@expense.amount).positive?
      @category_expenses = @category.expenses.to_a
      total_expenses_amount = @category_expenses.sum { |expense| BigDecimal(expense.amount) }

      if total_expenses_amount > @category.limit
        redirect_to new_category_expense_path, notice: 'Ops! Your expense amount is greater than your limit amount'
        return
      end
    else
      redirect_to new_category_expense_path, notice: 'Please enter a valid expense amount'
      return
    end

    if @expense.save
      @category.expenses << @expense
      redirect_to category_expenses_path(@category), notice: 'Successfully created an expense 🎉!'
    else
      render :new
    end
  end

  # PATCH/PUT /expenses/1 or /expenses/1.json
  def update
    @expense = Expense.find(params[:id])
    @category = Category.find(params[:category_id])

    return unless @category

    @category_expenses = @category.expenses.to_a
    total_expenses_amount = @category_expenses.sum(&:amount) - (@expense.amount.to_i || 0)

    if total_expenses_amount + params[:expense][:amount].to_i <= @category.limit
      if @expense.update(expense_params)
        redirect_to category_expenses_path, notice: 'Expense updated successfully 😊!'
      else
        flash.now[:alert] = 'Failed to update expense.'
        render :edit
      end
    else
      redirect_to edit_category_expense_path(@expense),
                  notice: 'Updating this expense would exceed the category limit.'
    end
  end

  # DELETE /expenses/1 or /expenses/1.json
  def destroy
    @expense = Expense.find(params[:id])
    @expense.destroy
    redirect_to category_expense_path
    flash[:notice] = 'Expense deleted 👋 !'
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:category_id])
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount).merge(author_id: current_user.id)
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def generate_color(category_name)
    @color_cache ||= {}
    @color_cache[category_name] ||= generate_random_color
  end

  private

  def generate_random_color
    pastel_colors = ['#ffb6c1', '#b0e0e6', '#98fb98', '#e6e6fa']
    unused_colors = pastel_colors - @color_cache.values
    if unused_colors.empty?
      @color_cache.clear
      unused_colors = pastel_colors
    end
    color = unused_colors.sample
    @color_cache.invert[color] = color
  end
end

app/views/expenses/_expense.html.erb
<div id="<%= dom_id expense %>"  class='category-details'>
  <div class='category-name-date' >
    <p class="generate-category-avatar" style="background-color: <%= generate_color(expense.name) %>"><%= expense.name[0].upcase %></p>
    <div class='category-date'>
      <p class="expense-name"><%= expense.name%></p>
      <p class='small-fade mobile-date'><%= expense.created_at.strftime('%B %d, %Y') %></p>
    </div>
  </div>
  <div class='limit-balance'>
    <div>
      <p class="expense-amount"><%= number_to_currency(expense.amount) %></p>
    </div>
  </div>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, url: category_expense_path(@category, expense), local: true) do |form| %>
  <% if expense.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.text_field :name, class: "form-input"%>
  </div>

  <div>
    <%= form.number_field :amount, class: "form-input" %>
  </div>

  <div class="submission-btn-div">
    <%= form.submit class: "submit-button" %>
    <%= link_to "Go Back", request.referrer || root_path, class: 'submit-button' %>

  </div>
  
<% end %>

app/views/expenses/edit.html.erb
<div class='category-index'>
  <div class='category-card'>
    <div class='grid-80'>
      <div class="inner-layer">
        <%= render partial: 'shared/nav' %>
        <div class="form-div">
          <h3 class="form-ribbon">Editing <%= @expense.name %> </h3>
          <p class='notice' style="color: red"><%= notice %></p>
          <%= render "form", expense: @expense %>
        </div>
      </div>
    </div>
    <%= render partial: 'shared/grid-20' %>
  </div>
</div>

app/views/expenses/index.html.erb
<div class='category-index'>
  <div class='category-card'>
    <div class='grid-80'>
      <div class="inner-layer">
        <%= render partial: 'shared/nav' %>
          <div class="add-expense-div">
            <p class='notice' style="color: green"><%= notice %></p>
            <div class='expense-and-total-amount'>
              <p class='category-expense-name'><%= category_name = @category.name %> </p> 
              <div>
                <p class='category-expense-amount'>Spent: <%= number_to_currency(@total_amount) %> </p> 
                <p class='category-expense-amount'>Bal: <%= number_to_currency(@category.limit - @total_amount) %> </p> 
              </div>
              <div>
                <% if @total_amount >= @category.limit %>
                  <p class='limit-reached'>Limit for <b> <%= @category.name %> </b> reached</p> 
                <% else %>
                  <p class="plus-and-text">
                    <%= link_to "+", new_category_expense_path(user_id: current_user.id, category_id: @category.id), 
                    class: 'add-expense-plus'%> <%= link_to "Add Expense", new_category_expense_path(user_id: current_user.id, category_id: @category.id), class: 'add-expense-btn' %></p>
                <% end %>
              </div>
            </div>
          </div>
          <%=  link_to 'Back to Categories', categories_path, class: 'expenses-to-categories'%>
          <div id="categories" class="allCategoryExpenses">
              <% if @expenses.empty?%> 
                <p class='no-categories'>You have no expenses for <b> <%= @category.name %> </b> </p>
              <% else %>
              <% @expenses.each do |expense| %>
              <div class='eachExpense'>
                <div>
                  <%= render expense %>
                </div>
                <div class='delete-edit'>
                  <%= link_to edit_category_expense_path(category_id: @category.id, id: expense.id)do %>
                    <%= image_tag 'editing.png', class: 'edit-pen' %>
                  <% end %>
                  <p class="fade-text"> <%= button_to 'X',category_expense_path(@category, expense), method: :delete, class: 'category_delete_botton' %> </p>
                </div>
              </div>
              <% end %>
            <% end%>
          </div>
      </div>
    </div>
    <%= render partial: 'shared/grid-20' %>
  </div>
</div>

app/views/expenses/new.html.erb
<div class='category-index'>
  <div class='category-card'>
    <div class='grid-80'>
      <div class="inner-layer">
        <%= render partial: 'shared/nav' %>
        <div class="form-div">
           <%= flash[:notice] %>
          <%= form_with(model: @expense, url: category_expenses_path(user_id: current_user.id, category_id: @category.id), local: true, remote: true) do |form| %>
            <h3 class='new-expense-ribbon form-ribbon'>Add expense for <b style='color: blue;'> <%= @category.name %> </b> </h3>
            <div class='expense-inputs'>
              <div>
                <%= form.text_field :name, class: 'field expense-field', placeholder: 'Expense name', class: "form-input" %>
              </div>
              <div>
                <%= form.number_field :amount, class: 'field expense-field', placeholder: 'Amount ($)', class: "form-input" %> <br>
              </div>
              <div class="submission-btn-div">
                <%= form.submit class: "submit-button" %>
                <%= link_to "Go Back", request.referrer || root_path, class: 'submit-button' %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <%= render partial: 'shared/grid-20' %>
  </div>
</div>

app/views/expenses/show.html.erb
<p style="color: green"><%= notice %></p>
<%= render @expense %>
<div>
  <%= link_to "Edit this expense", edit_expense_path(@expense) %> |
  <%= link_to "Back to expenses", expenses_path %>
  <%= button_to "Destroy this expense", @expense, method: :delete %>
</div>